#!/bin/bash
#
# copy contents of /var/log/messages to /var/log/messages.old
# delete the contents of /var/log/messages
# Usage: ./mssglogrotate

LOGFILE=/var/log/messages

cp $LOGFILE $LOGFILE.old
cat /dev/null > /var/log/messages
echo log file copied and cleaned up

exit 0 